export const INSTRUMENT_TYPE = {
  accordian: 'accordéon',
  air_horn: 'klaxon à air',
  baby_grand_piano: 'bébé piano à queue',
  bagpipe: 'cornemuse',
  banjo: 'banjo',
  bass_guitar: 'guitare basse',
  bassoon: 'basson',
  bugle: 'clairon',
  calliope: 'calliope',
  cello: 'violoncelle',
  clarinet: 'clarinette',
  clavichord: 'clavicorde',
  concertina: 'concertina',
  didgeridoo: 'didgeridoo',
  dobro: 'dobro',
  dulcimer: 'tympanon',
  fiddle: 'violon',
  fife: 'fifre',
  flugelhorn: 'bugle',
  flute: 'flûte',
  french_horn: 'Cor français',
  glockenspiel: 'glockenspiel',
  grand_piano: 'grand piano',
  guitar: 'guitare',
  harmonica: 'harmonica',
  harp: 'harpe',
  harpsichord: 'clavecin',
  hurdy_gurdy: 'vielle à roue',
  kazoo: 'kazoo',
  kick_drum: 'grosse caisse',
  lute: 'luth',
  lyre: 'lyre',
  mandolin: 'mandoline',
  marimba: 'marimba',
  mellotran: 'mellotran',
  melodica: 'mélodica',
  oboe: 'hautbois',
  pan_flute: 'flûte de pan',
  piano: 'piano',
  piccolo: 'piccolo',
  pipe_organ: 'orgue',
  saxaphone: 'saxophone',
  sitar: 'sitar',
  sousaphone: 'sousaphone',
  tambourine: 'tambourin',
  theremin: 'thérémine',
  trombone: 'trombone',
  tuba: 'tuba',
  ukulele: 'ukulélé',
  viola: 'alto',
  violin: 'violon',
  vuvuzela: 'vuvuzela',
  washtub_bass: 'basse de lavabo',
  xylophone: 'xylophone',
  zither: 'cithare',
};
