export const INSTRUMENT_TYPE = {
  accordian: 'Accordéon',
  air_horn: 'Klaxon à air',
  bagpipe: 'Cornemuse',
  banjo: 'Banjo',
  bass_guitar: 'Basse',
  bassoon: 'Basson',
  bugle: 'Clairon',
  calliope: 'Calliope',
  cello: 'Violoncelle',
  clarinet: 'Clarinette',
  bass: 'Contrebasse',
  clavichord: 'Clavicorde',
  concertina: 'Concertina',
  didgeridoo: 'Didgeridoo',
  dobro: 'Dobro',
  dulcimer: 'tympanon',
  flugelhorn: 'Bugle',
  flute: 'Flûte',
  french_horn: 'Cor français',
  guitar: 'Guitare',
  harmonica: 'Harmonica',
  harp: 'Harpe',
  harpsichord: 'Clavecin',
  kazoo: 'Kazoo',
  lute: 'Luth',
  lyre: 'Lyre',
  mandolin: 'Mandoline',
  marimba: 'Marimba',
  mellotran: 'Mellotran',
  melodica: 'Mélodica',
  oboe: 'Hautbois',
  pan_flute: 'Flûte de pan',
  piano: 'Piano',
  piccolo: 'Piccolo',
  pipe_organ: 'Orgue',
  saxaphone: 'Saxophone',
  sitar: 'Sitar',
  sousaphone: 'Sousaphone',
  tambourine: 'Tambourin',
  theremin: 'Thérémine',
  trombone: 'Trombone',
  tuba: 'Tuba',
  ukulele: 'Ukulélé',
  viola: 'Alto',
  violin: 'Violon',
  vuvuzela: 'Vuvuzela',
  washtub_bass: 'Contrebassine',
  xylophone: 'Xylophone',
};

export const LIST_INSTRUMENT_TYPE = Object.keys(INSTRUMENT_TYPE).map((k) => ({
  label: INSTRUMENT_TYPE[k],
  slug: k,
}));
